### ISSUE TITLE
how to set cert store to use webpki-roots 

### ISSUE THREAD

**Issue by vangork** [0x676e67/rquest#129]
When I use this crate to connect to my web server on Windows 11, got the error of `unable to get local issuer certificate`.(my web server uses a let's encrypted issued free cert)

After some research, it seems that boring itself would not ship with any root certificates. And it seems that it dosen't read the user root cert store correctly on Windows, 

So is that possible to integrate [webpki-roots](https://github.com/rustls/webpki-roots) as defaut cert store just like rustls dose during initializing boring sslconnector?

**Comment by 0x676e67** [comment]
https://github.com/0x676e67/rquest/blob/main/examples/set_ca_cert.rs#L11

**Comment by 0x676e67** [comment]
This is the setup of a series of certificates, why don’t you try it?

**Comment by 0x676e67** [comment]
Or specify the path yourself：https://github.com/sfackler/rust-openssl/pull/535/files

**Comment by 0x676e67** [comment]
https://github.com/cloudflare/boring/blob/a7bfe0d92c01f55faf21c0dca378eeb5753a351e/boring/src/ssl/mod.rs#L1137

Is this not what you want to load a list of certificates? Or are you not even trying?

**Comment by 0x676e67** [comment]
For webpki-roots, BoringSSL currently has no compatible API. It would be great if you are willing to PR a wheel solution.
